### ISSUE TITLE
[FR] call register_hooks with positional arguments rather than keyword

### ISSUE THREAD

**Issue by c8y3** [dfir-iris/iris-web#173] opened 2023-01-23 10:19 UTC
**Is your feature request related to a problem? Please describe.**
As a plugin developer, I would like to choose the name of the parameter of register_hooks (to call it module_identifier rather than module_id). However, because register_hooks is called with keyword arguments (see https://github.com/dfir-iris/iris-web/blob/v2.0.0-beta-2/source/app/iris_engine/module_handler/module_handler.py#L282 and https://github.com/dfir-iris/iris-web/blob/v2.0.0-beta-2/source/app/iris_engine/module_handler/module_handler.py#L308), the name of the parameter can not be changed.

**Describe the solution you'd like**
Instead of calling register_hooks with keyword arguments, the positional convention could be followed (replace `mod_inst.register_hooks(module_id=module_id)` by `register_hooks(module_id)`. This would allow the module developer to freely choose the name of the parameter

**Comment by whikernel** [comment] 2023-01-26 17:41
Hi @c8y3!  

This is open for discussion, but I would prefer to have common parameter names for calls in the interface. This will greatly help us review the plugin/modules later on. 
Also, if we call the interface methods with positional args we might end up with unexpected behavior because someone swapped them inadvertently. This isn't an issue with one arg methods like  `register_hooks` but it might be for `hooks_handler` for instance. 
Let me know what you thing.

**Comment by c8y3** [comment] 2023-01-27 07:18
No problem. It was just a suggestion. You can keep it that way if you want.
But, then it would still be nice to handle the exception that is raised when the argument name is incorrect. If the interface (and logs) returns an explicit message that the signature of the method is incorrect and suggests the explicit signature, then it would be easier for a plugin developer to understand the problem.
Thank you.

**Comment by whikernel** [comment] 2023-01-27 08:12
Indeed, we'll look toward better logging and exception handling in modules 👍  
I'll then close this issue, thanks for raising that up

**Closed by whikernel** 2023-01-27 08:12 UTC
Labels: enhancement
