### ISSUE TITLE
[BUG] Docker compose build fails on fresh install (Debian 12)

### ISSUE THREAD

**Issue by 0xFA15E5EC** [dfir-iris/iris-web#387] opened 2024-01-18 22:51 UTC
This issue does not depend on the host environment or docker configuration.
This issue pertains to the v2.4.4 tagged checkout.

Following the provided instructions: git clone, git checkout, cp the .env file, docker compose build, docker compose up
  results in a non-functioning iriswebapp_app and iriswebapp_db.

Digging into the root cause for the inaccessible web app on port 8000, I identified the following error resident on the database container:

[PG::UndefinedFunction: ERROR: function gen_random_uuid()

This function does not exist on postgres 12, it's new in v13.

This error can be fixed by running:
sed -i  's/12-alpine/13-alpine/' iris-web/docker/db/Dockerfile

then rebuild the docker containers:
docker compose build --no-cache
docker compose up

I didn't submit a pr, as I'm not sure if there is any particular reason the postgres:12-alpine container is used.

**Comment by StaSys846** [comment] 2024-01-19 09:13
I had the same issue for a clean setup of iris (new database). The root cause of that issue was unclear, but it is related to a missing extension in postgresql DB. A manual extension install in postgresql fixed the issue:
1. connect to postgres DB after initial setup of iris and getting the before mentioned error (standard user is postgres and postgres db password should be in your .env file)
2. select iris_db database: `\c iris_db`
3. Execute following command: `CREATE EXTENSION pgcrypto;`

After that Iris will start up as expected.
Normally that should happen during iris start, but the reason was unclear for me why it was not done by iris itself (code is present and should have been executed). Since it was only for testing, a deeper root cause analysis was skipped. Hope that helps.

**Comment by whikernel** [comment] 2024-01-19 11:13
We found a fix, we'll release a patch within the next hours

**Comment by whikernel** [comment] 2024-01-19 12:05
This should now be fixed in v.2.4.4.

**Closed** 2024-01-19 20:36 UTC
Labels: bug
