### ISSUE TITLE
[BUG] special characters in the field alert_source_content are not working

### ISSUE THREAD

**Issue by CyberAbwehr** [dfir-iris/iris-web#296] opened 2023-08-28 13:22 UTC
**Describe the bug**
Sending alerts from wazuh to DFIR-IRIS API, 
alert_source_content with special character

"alert_source_content": "Trojaned version of file '/usr/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic)."

is not working.

The special characters are important information for the security analysts.

**To Reproduce**

#!/bin/bash
curl --request POST \
--url http://192.168.56.103:8001/alerts/add \
--header 'Authorization: Bearer j54xHsdyM5w-_UZmjAr6BIuFSsrMB1qE892Qtp1Rw6aJ9ehDRFP-UxmV1wuwv1VLTxT9KwJVsBuA7iAsMtKn_Q' \
--header 'Content-Type: application/json' \
--data '{
  "alert_title": "Host-based anomaly detection event (rootcheck).",
  "alert_description": "Host-based anomaly detection event (rootcheck).",
  "alert_source": "shuffle 10.0.2.15",
  "alert_source_ref": "Wazuh Alert",
  "alert_source_link": "https://192.168.56.102/app/wazuh",
  "alert_severity_id": "1",
  "alert_status_id": "3",
  "alert_source_event_time": "2023-08-24T13:53:21",
  "alert_note": "${alert_note}",
  "alert_tags": "wazuh",
  "alert_customer_id": "1",
  "alert_classification_id": "1",
  "alert_source_content": "Trojaned version of file '/usr/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic)."
  }'

You need to change ip, port and token

**Expected behavior**
to see the full string from the field alert_source_content at Raw Alert (Toggle Raw Alert)

**Screenshots**
no screenshots

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Firefox

**Comment by whikernel** [comment] 2023-09-04 19:04
Hi @CyberAbwehr 

I don't manage to replicate the issue. Please see: https://v200.beta.dfir-iris.org/alerts?cid=1&page=1&per_page=10&sort=desc&alert_ids=1756 

I had to change your request because the  '  isn't escape in your alert_source_content and thus breaks the string. 
Please let me know if I missed something 

Cheers

**Comment by whikernel** [comment] 2024-02-23 14:25
Hi @CyberAbwehr 

I still don't manage to replicate. 
From what I see the problem is not really in the special chars, but more in the fact that the body of the request is a broken JSON. 
In your example the `'` isn't escape which makes the bash broken. Once escaped, it works.  
Putting the raw string in the content using POSTMAN works by default: 

<img width="647" alt="image" src="https://github.com/dfir-iris/iris-web/assets/74464599/fb2bba72-5f3a-4206-9879-f62538246f36">

<img width="1264" alt="image" src="https://github.com/dfir-iris/iris-web/assets/74464599/0b5484c3-0690-4cf6-88ff-829a541c2d02">
<img width="1386" alt="image" src="https://github.com/dfir-iris/iris-web/assets/74464599/5a9b3b3e-a2df-49d5-b866-03723e600244">

**Comment by whikernel** [comment] 2024-04-24 15:38
Hi! 
I'm closing this issue to clean up - if you still have the problem please don't hesitate to reopen the issue.

**Closed by whikernel** 2024-04-24 15:38 UTC
Labels: bug
